title: "whohe"
email: wilsonhernandezortiz@gmail.com
timezone: America/Bogota
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: will
paginate: 30
disqus: 'disqus_D32p0YuZHC'
locale: es_co
lang: es_co
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  will:
    name: Wilson
    display_name: Will
    avatar: 'assets/images/will.jpg'
    email: wilsonhernandezortiz@gmail.com
    web: https://whohe.github.io
    description: "Entusiasta de la tecnología, apasionado por el desarrollo de aplicaciones móviles con Android e Ionic."

# Social
social:
  instagram: #
  facebook: #
  twitter: #

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
